SkynetLabs/skynet-accounts

database/database.go
go.mod
go.sum

This PR doesn't add indexes on the `_id` field because MongoDB [creates one automatically](https://docs.mongodb.com/manual/indexes/#default-id-index).
Closes #18

Ensure DB schema on service start.

---

api/cookie.go
api/handlers.go
database/database.go
database/download.go
database/upload.go
database/user.go
main.go

* Introduce Response DTOs, so we can control how the data is represented in our responses.
* Tweak the data content and structure according to @kwypchlo's needs.
* Always use UTC time.
* Switch the time representation in the DB from primitive.Timestamp to time.Time.
Example responses:
```json
[
{
"id": "601c10a1fc760d69e53f1092",
"skylink": "HELLO__5MJyl1DKyfbuQMY_XBOBC9bR7idiU6isp6LXxEw",
"name": "This is my HELLO skyfile!",
"size": 132412341234,
"uploaded_on": "2021-02-04T15:20:01.577Z"
}
]
```
```json
[
{
"id": "601c1626df96cb02cd2e84a0",
"skylink": "HELLO__5MJyl1DKyfbuQMY_XBOBC9bR7idiU6isp6LXxEw",
"name": "This is my HELLO skyfile!",
"size": 132412341234,
"downloaded_on": "2021-02-04T15:43:34.871Z"
}
]
```

Upload/Download Response DTOs

---

api/handlers.go
api/routes.go
database/database.go
database/download.go
database/upload.go
database/user.go
metafetcher/fetcher.go
skynet/bandwidth.go
skynet/bandwidth_test.go
test/upload_test.go
test/user_test.go

* Introduced a new `/user/stats` endpoint that reports on various user stats, such as storage and bandwidth used.
* Used storage is no longer stored with the user's record, making it moot for the fetcher to update the user.
* Increment download size of the most recent download instead of creating a new one.
Most of these are pretty straightforward, with the exception of the incremental downloads. What is happening there is that when `accounts` receives a request to track a new download, before it does so it would check whether there is a recent download by the same user of the same skylink. "Recent" is adjustable and is currently set to 10 minutes. If there is such a recent upload, we won't create a new one and instead we are just going to increment the size of the recent download with …

Implement user statistics endpoint

---

README.md
api/handlers.go
api/routes.go
api/stripe.go
database/skylink.go
database/skylink_test.go
database/upload.go
database/user.go
database/user_test.go
go.sum
jwt/jwt.go
main.go
metafetcher/fetcher.go
skynet/bandwidth.go
skynet/bandwidth_test.go
test/upload_test.go
test/user_test.go

This PR introduces three new endpoint:
* `GET /user/limits` returns the speed limits for the user based on their account tier. It takes care to downgrade the speed of the user if they exceed their quotas.
* `DELETE /skylink/:skylink` marks the given skylink as unpinned by the current user (all uploads)
* `DELETE /user/upload/:uploadId` marks the given upload as unpinned
~~It also changes the way we calculate storage and bandwidth used by the user to be closer to the real world usage. See https://discord.com/channels/542938080349519882/542939275587485696/821722719069405184 and the subsequent discussion.~~  
Uploaded files now count towards the uploader's quota with their normal size (as seen when the file is on disk) and not based on on the raw size on the Sia network.
Each account tier …

Endpoints for speed limits and unpinning files

---

api/handlers.go
api/routes.go

* The health check always returns 200 when the service is alive.
* The body of the health check contains a JSON with the status of the database which can be `true` or `false` (if the DB is down)
I don't mind changing the way this works to return an error code when the DB is down instead of a 200 - both would make sense to me.

Add a simple health check.

---

main.go

This PR fixes a minor but annoying problem with loading environment variables. The result is a cryptic error message (e.g. `2021/09/29 10:57:05 <nil>`) when one of the new required env vars is not set. This is not helpful.
Old output: `2021/09/29 10:57:05 <nil>`
New output: `2021/09/29 13:28:58 ACCOUNTS_EMAIL_URI is empty`

Fix an error output

---

database/user.go

This PR temporarily lowers the `anon` tier download limits to reduce over all download pressure on our production nodes. I applied a `/4` on all download related limits.
N/A
N/A

Lower Tier Limits

---

changelog/items/key-updates/base32.md
database/skylink.go
database/skylink_test.go

Add support for base32 skylinks.
This closes #98 and allows `blocker` and `malware-scanner` to work with base32 skylinks, as well.

Add support for base32 skylinks.

---

main.go

Having the TTL of our JWTs hardcoded is not ideal - portal operators should be able to decide how much risk they want to take on their users's behalf. Also, we want to be able to change that in order to test various features we are working on.
To address the above, this PR adds a new environment variable called `ACCOUNTS_JWT_TTL` which specifies the TTL of JWTs in seconds.

Add an env var that controls the TTL of our JWTs.

---

api/api.go
api/routes.go
api/stripe.go
database/user.go
go.mod
go.sum

Recently we've had some issues with DB writes being cancelled because of overlapping changes. One way we can resolve that is to make sure that we use DB sessions only when we actually need them (read then write, write to multiple documents, etc.). This PR does that. 

Don't start DB sessions if we don't need them

---

.github/dependabot.yml
Dockerfile

- include Dockerfile (to enable docker hub builds)
- include dependabot config to make sure the image dependencies are up to date
- update golang image from 1.17.3 to 1.17.7
- introduced multi stage build - build with debian and copy binary to alpine image to reduce image size
- updated maintainer email address
- removed redundant GOOS and GOARCH env vars - those are golang image defaults anyway
- added CGO_ENABLED=0 to indicate that the resulting binary has to be standalone (required to run on alpine)

add dockerfile and dependabot config

---

api/cache.go

When reporting the user's tier, we check whether their subscription has expired and, if it has, we report `free`, regardless of their tier. This causes issues with users who are promoted manually, without having a running subscription.
The solution is to not do this manual check and rely on the Stripe webhook to take care of subscription levels.

Fix /user/limits reporting wrong tier

---

API.md
main.go

Add API docs for general API keys.

---

api/cache.go
api/cache_test.go
api/handlers.go
database/challenge.go
test/api/api_test.go
test/api/apikeys_test.go
test/api/challenge_test.go
test/api/handlers_test.go
test/email/sender_test.go
test/tester.go

When a user exceeds their quota, /user/limits will keep returning their tier and tier name but the speed limits will match anonymous tier levels.
Note: This PR also includes the now infamous `ul.TierName != database.UserLimits[database.TierPremium20].TierName` fix that we've already seen in another PR. I might remove it from there and merge it here.
Fixes: #145

Fix /user/limits quotaExceeded

---

api/routes.go
database/apikeys.go
database/apikeys_test.go

API keys use `base32` encoding which is using an all-caps alphabet. We want, however, to allow users to send their API keys in lower case, as well. This will make the user experience smoother.

Handle API keys passed in their lower case form.

---

api/routes.go
database/skylink.go
database/upload.go
main.go

This PR fixes a problem caused by a race condition.
The race condition happens when we try to fetch a skylink from the database, we don't find it, so we decide to insert it. When inserting it, we use `upsert` in order to avoid overwriting the ID if it just so happens that another server creates that exact skylink in that very moment. The issue is that in that case the upsert operation does not do anything and it does not return an `UpsertID`. This leaves the skylink record returned by the function with a valid hash but an empty ID. This empty ID later on causes this skylink to be evaluated as invalid.
This PR makes two changes:
- instead of "invalid skylink" we now return "skylink doesn't exist" to better capture the situation of an empty ID
- ~~we specifically check whether the …

Skylink race

---

api/handlers.go
test/api/api_test.go
test/api/handlers_test.go
test/tester.go

The `/limits` endpoint returns the bandwidth limits in bits per second, which is the format most people expect to see.
The `/user/limits` endpoint, though, returns the bandwidth in bytes per second because that is what Nginx expects to see.
This discrepancy is very confusing for users and it needs to be resolved. To that end this PR adds a new query parameter which would let Nginx request the limits in bytes (see https://github.com/SkynetLabs/skynet-webportal/pull/1855) while everyone else will receive the limits in bits.

/user/limits in bits or bytes

---

api/handlers.go
database/user.go
skynet/bandwidth.go
skynet/bandwidth_test.go
test/api/handlers_test.go
test/database/upload_test.go
test/database/user_test.go

Based on our discussion, we want to switch from using KiB, Kib, MiB, Mib to kB, kb, MB, Mb, i.e. go from 1024 to 1000.

Use base 10 units instead of base 2 units

---

api/handlers.go

When a user exceeds their quota limit only their speed, not the rest of their allowance.

When a user exceeds their quota limit only their speed

---

.github/workflows/dockerfile-lint.yml

Lint dockerfile with https://github.com/hadolint/hadolint-action
ref. https://github.com/hadolint/hadolint
local scan: `docker run --rm -i hadolint/hadolint < Dockerfile`

Lint dockerfile with hadolint

---

api/cache.go
api/cache_test.go
api/handlers.go
api/handlers_test.go
test/api/api_test.go
test/api/apikeys_test.go
test/api/handlers_test.go

Add the user's sub to the information returned by /user/limits, so that can be cached and cross-referenced later in nginx's access logs.
Closes #181

Add the user's sub to the information returned by /user/limits

---

api/routes.go
api/stripe.go
go.mod
go.sum
main.go
test/api/stripe_test.go
test/tester.go

This PR introduces three new endpoints for talking to Stripe. These were previously implemented under the portal code but we want to get rid of the portal code's backend component.
Closes #157

Stripe Endpoints

---

api/cache_test.go
database/apikeys.go
database/user.go
test/api/handlers_test.go

Fix user creation time being zero.

---

api/handlers.go
database/database.go
database/schema.go
test/api/handlers_test.go

As we have high priority work that trumps DB performance tracking and optimisations, we wanted to have some quick wins before we park this effort. This PR provides those quick wins by removing registry tracking.
What's done here: Stop tracking registry accesses and drop all DB collections related to those.

Stop tracking registry accesses

---

database/database.go

Ignore "IndexNotFound" errors and log the rest without panicking.

---

api/handlers.go
test/api/handlers_test.go

As discussed previously, requiring the user's email to be confirmed in order to recover their account is too much of a limitation and we should remove it. This PR does that.

Allow account recovery from unconfirmed emails.

---

api/routes.go
api/stripe.go
test/api/stripe_test.go
test/database/user_test.go
test/tester.go

Change the http verb of /stripe/billing from POST to GET.

---

Makefile
build/build.go
build/debug_off.go
build/debug_on.go
build/release_dev.go
build/release_standard.go
build/release_testing.go
main.go

Print commit hash and build time.

---

api/routes.go
test/api/apikeys_test.go

Allow API keys on additional endpoints.

---

env/Dockerfile

Karol reported that while running `make docker-generate` on xyz he encountered
```
/go/pkg/mod/github.com/ory/x@v0.0.368/jsonx/get.go:19:13: f.IsExported undefined (type reflect.StructField has no field or method IsExported)
The command '/bin/sh -c go get github.com/ory/hydra/jwk' returned a non-zero code: 2
make: *** [Makefile:165: docker-generate] Error 2
```
and I confirmed that locally. Upgrading the go image to 1.18 fixes the incompatibility.

Use go 1.18 for the JSWKS generator.

---

.github/workflows/ci_release.yml
Makefile
api/handlers_test.go
test/api/api_test.go
test/api/handlers_test.go
test/api/stripe_test.go
test/database/apikeys_test.go
test/database/challenge_test.go
test/database/configuration_test.go
test/database/upload_test.go
test/database/user_test.go
test/email/sender_test.go
test/setup.sh
test/utils.go
types/email_test.go

This PR fixes some lint errors, cleans up the Makefile, addresses missed `testing.Short()` calls, and enables the long tests in CI.

Enable test-long in CI

---

Makefile
api/handlers_test.go
build/debug_off.go
build/debug_on.go
build/release_dev.go
build/release_standard.go
build/release_testing.go
types/email_test.go

We inadvertently made some changes which break the logic of some unit tests. I'm reverting those changes here, adding some context and adding some other clean-ups.
The [original PR](https://github.com/SkynetLabs/skynet-accounts/pull/222) mentions lint issues. If the changes reverted here were fixes for linting issues then we should fix the linting setup in `Makefile` because I'm not getting any warnings/errors.

Revert some changes

---

Makefile

Executing `make docker-generate` sometimes doesn't create `jwks.json` and sometimes it creates empty file.
This PR updates sleep timeout for file creation so that generating the file via Ansible is more reliable.

Increase timeout for generating env, jwks.json files
