SkynetLabs/skynet-accounts

- Makefile
- api/api.go
- api/handlers.go
- database/database.go
- database/user.go
- database/user_test.go
- main.go
- test/database_test.go
Note: I kept losing my todo notes, so I just committed them in this one. I need to address them soon anyway, so it should be fine for us to have some TODOs in the code while we're iterating quickly.
This MR does not cover the two `User`-related items in #5, we need to finalize our consensus on those first. Please feel free to chime in.
Closes #5
> Implement follow-ups on the initial commit

- database/user.go
When adding the `/user/stats` endpoint, I limited the calculations to the current month because the bandwidth limits should reset at the end of the month. But used storage needs to be calculated on a global scale and not limited to the current month. This PR fixes that.
> Used storage should be calculated regardless or the current month.

- api/handlers.go
- database/user.go
Switch to using Mongo's Ping method.
> Improved healthcheck

- api/handlers.go
- api/routes.go
- database/user.go
Exposes an endpoint which requires no authentication and lists all speed limits of the portal. Currently, those are just the limits different tiers of user accounts have. In the future we might add others as well.
> Public limits endpoint

- api/handlers.go
- api/routes.go
- api/stripe.go
This is a preparatory PR for implementing user registration.
> Rename handlers to match their verbs.

- CHANGELOG.md
- changelog/.changelogignore
- changelog/README.md
- changelog/changelog-head.md
- changelog/changelog-tail.md
- changelog/generate-changelog.sh
This adds the same changelog generator that skyd has been using.
> Add changelog generator and initial Changelog

- database/skylink.go
> fix interface conversion panic

- README.md
Fix outdate accounts uri format 
> update README for accounts uri

- Makefile
With more tests and more linting, we need more time to run those.
Closes #117
> Increase test runtime limit

- api/stripe.go
For some reason some subscriptions returned by Stripe's API had empty IDs. We can't cancel those, so we shouldn't even try.
I added some quotes around all string values in order to make such logs easier to read in the future.
> Don't try to cancel subscriptions with empty IDs.

- test/api/handlers_test.go
- test/tester.go
This PR adds tests which ensure that on login we return a JWT within the `Skynet-Token` header of the response and that this JWT is valid.
Closes #116
> Add tests ensuring the presence and validity of Skynet-Token.

- api/handlers.go
> Do not disclose whether a user exists or not on failed login attempt.

- api/apikeys.go
- api/handlers.go
- database/user.go
- test/api/handlers_test.go
- test/database/upload_test.go
- test/database/user_test.go
This PR started as a branch for one minor follow up and a couple more were added.
The only change that leads to behaviour change is the `omitempty` annotations to `APIKeyPOST`.
> [MINOR] A collection of minto follow up actions

- api/handlers.go
- api/routes.go
- api/upload.go
- database/upload.go
- test/api/handlers_test.go
- test/api/upload_test.go
- test/tester.go
Implement `GET /uploadinfo/:skylink`
> Implement `GET /uploadinfo/:skylink`

- .github/dependabot.yml
> Run dependabot monthly instead of weekly.

- api/handlers.go
- database/skylink.go
- database/user.go
- test/api/apikeys_test.go
Create a list of always allowed skylinks in order to make MySky always available on all portals.
Closes #204
> MySky Allowlist

- api/stripe.go
- test/api/stripe_test.go
Instruct Stripe's API to expand the product, associated with the price, so we can display its description.
> Fix Stripe product description display

- .github/workflows/ci_release.yml
This fixes the release action and adds the docker publish action. 
> Fix release and add docker publish

- Makefile
> Remove test-int and move its logic under test-long.

- api/handlers.go
- api/routes.go
- api/upload.go
- database/upload.go
- test/api/upload_test.go
- test/tester.go
- test/utils.go
> List recently uploaded skylinks

- README.md
> Add example code for solving the login challenge to README.

- api/handlers.go
- api/upload.go
- database/database.go
- database/user.go
- email/sender.go
- go.mod
- go.sum
- jwt/jwt.go
- lib/util.go
- test/api/upload_test.go
- test/setup.sh
> Implement a better health endpoint.

- api/stripe.go
> Return an informative error when Stripe is not configured.

- api/api.go
- api/routes.go
- main.go
- test/api/api_test.go
- test/api/handlers_test.go
- test/api/promoter_test.go
- test/api/stripe_test.go
- test/api/upload_test.go
- test/tester.go
Add an env var that switches between Stripe and Promoter as payment processor.
> Promoter / Stripe switch
